apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labeles: 
    project: digiapp
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is used for annotations"
    Azure_Pipeline: "https://Azure.services.digiGst/DigiGST_UI/app-release/33456/"
spec:
  containers:
  - name: nginx
    image: nginx
