apiVersion: v1
kind: Pod
metadata: 
  name: resources

spec:
  containers:
  - name: nginx
    image: nginx
  resources: 
    requests:   # softlimit 
      memory: "100mi"
      cpu: "100m"
    limits:
      memory: "120mi"
      cpu: "150m"    