apiVersion: v1
kind: Secrets
metadata:
  name: pod-Secret
  labeles:
    purpose: Secrets
    environment: uat
type: Opaque # it nothing but user defind data
data:  # here encoded base 64 mechanisim  ( echo - n "admin" | base64 )
  USER_NAME: "YWRtaW4="   # echo  YWRtaW4= | base64 decode  ) for  for decoding 
  PASS_WORD: "YWRtaW4xMjM="

   