apiVersion: v1
kind: Pod 
metadata:
  name: pod-Secret
  labeles: 
    purpose: env-Secretconfig
    env: uat 
spec:
  containers: 
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:   
          name: pod-secret  # the secret config name
  